# Generated by Django 5.1.4 on 2025-01-13 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField(unique=True)),
                ('activities', models.TextField()),
            ],
        ),
    ]
